/*
 * Copyright by Zoltán Cseresnyés, Ruman Gerst
 *
 * Research Group Applied Systems Biology - Head: Prof. Dr. Marc Thilo Figge
 * https://www.leibniz-hki.de/en/applied-systems-biology.html
 * HKI-Center for Systems Biology of Infection
 * Leibniz Institute for Natural Product Research and Infection Biology - Hans Knöll Institute (HKI)
 * Adolf-Reichwein-Straße 23, 07745 Jena, Germany
 *
 * The project code is licensed under BSD 2-Clause.
 * See the LICENSE file provided with the code for the full license.
 */

package org.hkijena.acaq5.extensions.imagejdatatypes.datasources;

import org.hkijena.acaq5.ACAQDependency;
import org.hkijena.acaq5.api.algorithm.ACAQAlgorithmCategory;
import org.hkijena.acaq5.api.algorithm.ACAQAlgorithmDeclaration;
import org.hkijena.acaq5.api.algorithm.ACAQGraphNode;
import org.hkijena.acaq5.api.algorithm.AlgorithmInputSlot;
import org.hkijena.acaq5.api.algorithm.AlgorithmOutputSlot;
import org.hkijena.acaq5.api.algorithm.DefaultAlgorithmInputSlot;
import org.hkijena.acaq5.api.algorithm.DefaultAlgorithmOutputSlot;
import org.hkijena.acaq5.api.data.ACAQData;
import org.hkijena.acaq5.extensions.filesystem.dataypes.FileData;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Set;

/**
 * Declaration for {@link ImagePlusFromFile}
 */
public class ImagePlusFromFileAlgorithmDeclaration implements ACAQAlgorithmDeclaration {

    private String dataClassId;
    private Class<? extends ACAQData> dataClass;
    private List<AlgorithmInputSlot> inputSlots = new ArrayList<>();
    private List<AlgorithmOutputSlot> outputSlots = new ArrayList<>();

    /**
     * @param dataClassId the data class ID
     * @param dataClass   the data class generated by the algorithm
     */
    public ImagePlusFromFileAlgorithmDeclaration(String dataClassId, Class<? extends ACAQData> dataClass) {
        this.dataClassId = dataClassId;
        this.dataClass = dataClass;
        inputSlots.add(new DefaultAlgorithmInputSlot(FileData.class, "Input", false));
        outputSlots.add(new DefaultAlgorithmOutputSlot(dataClass, "Image", "", false));
    }

    @Override
    public String getId() {
        return dataClassId + "-from-file";
    }

    @Override
    public Class<? extends ACAQGraphNode> getAlgorithmClass() {
        return ImagePlusFromFile.class;
    }

    @Override
    public ACAQGraphNode newInstance() {
        return new ImagePlusFromFile(this, dataClass);
    }

    @Override
    public ACAQGraphNode clone(ACAQGraphNode algorithm) {
        return new ImagePlusFromFile((ImagePlusFromFile) algorithm);
    }

    @Override
    public String getName() {
        return "Import " + ACAQData.getNameOf(dataClass);
    }

    @Override
    public String getDescription() {
        return "Imports an image via native ImageJ functions";
    }

    @Override
    public String getMenuPath() {
        return "";
    }

    @Override
    public ACAQAlgorithmCategory getCategory() {
        return ACAQAlgorithmCategory.DataSource;
    }

    @Override
    public List<AlgorithmInputSlot> getInputSlots() {
        return Collections.unmodifiableList(inputSlots);
    }

    @Override
    public List<AlgorithmOutputSlot> getOutputSlots() {
        return Collections.unmodifiableList(outputSlots);
    }

    @Override
    public Set<ACAQDependency> getDependencies() {
        return Collections.emptySet();
    }

    @Override
    public boolean isHidden() {
        return false;
    }
}
