image: maven:3-eclipse-temurin-8-focal

stages:
  - build
  - package

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  PROJECT_VERSION: "4.0.0"

cache:
  paths:
    - .m2/repository

before_script:
  - apt-get update
  - apt-get install -y zip
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

maven_package:
  stage: package
  script:
    - mvn package
    - cd dist/zip
    - ./build.sh
  artifacts:
    paths:
      - dist/zip/JIPipe-${PROJECT_VERSION}.zip
