image: maven:3-eclipse-temurin-21-jammy

stages:
  - build
  - package

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GIT_STRATEGY: fetch

cache:
  paths:
    - .m2/repository

maven_build:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y git git-lfs zip unzip
    - git lfs install
  script:
    - mvn -B -V -DskipTests=true -Dmaven.javadoc.skip=true clean install
  artifacts:
    paths:
      - .m2/repository

distribution_package:
  stage: package
  needs: ["maven_build"]
  before_script:
    - apt-get update
    - apt-get install -y git git-lfs rsync zip unzip
    - git lfs install
  script:
    - git clone --depth 1 https://asb-git.hki-jena.de/RGerst/jipipe-distribution-files.git
    - cd jipipe-distribution-files/scripts
    - ./step1-publish-snapshot-ci.sh "" "${CI_PIPELINE_IID}"
    - ./step2-create-zip.sh
    - ./step3-build-packages.sh
    - cd ..
    - export OUTDIR="$(ls -d *-snapshot${CI_PIPELINE_IID} | head -n 1)"
    - test -n "$OUTDIR" || { echo "Snapshot output dir not found"; ls -lah; exit 1; }
  artifacts:
    name: "jipipe-distribution-snapshot-${CI_PIPELINE_IID}"
    when: always
    expire_in: 2 weeks
    paths:
      - jipipe-distribution-files/*-snapshot${CI_PIPELINE_IID}/*

