package org.hkijena.acaq5.api;

import java.util.Set;

/**
 * Base interface for an algorithm data trait
 * Traits are generated by data slots and accumulated over algorithm depth.
 * Algorithms can modify output traits by adding or removing them.
 */
public interface ACAQTrait {
}
