<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>jipipe-cwl-java</artifactId>
    <packaging>jar</packaging>
    <name>Common Workflow Language SDK (JIPipe)</name>
    <description>JIPipe distribution of cwl-java</description>
    <version>1.2.0</version>
    <parent>
        <artifactId>pom-jipipe</artifactId>
        <groupId>org.hkijena</groupId>
        <version>6.0.0-SNAPSHOT</version>
    </parent>
    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <commonslang.version>3.17.0</commonslang.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <license.licenseName>apache-2.0</license.licenseName>
        <license.copyrightOwners>N/A</license.copyrightOwners>
    </properties>
    <url>https://www.jipipe.org/</url>
    <inceptionYear>2025</inceptionYear>
    <organization>
        <name>Leibniz Institute for Natural Product Research and Infection Biology - Hans Knöll Institute (HKI)</name>
        <url>https://www.leibniz-hki.de/</url>
    </organization>
    <developers>
        <developer>
            <id>mr-c</id>
            <name>Michael R. Crusoe</name>
            <url>https://github.com/mr-c</url>
        </developer>
        <developer>
            <id>stain</id>
            <name>Stian Soiland-Reyes</name>
            <url>https://github.com/stain</url>
        </developer>
        <developer>
            <id>jdidion</id>
            <name>John Didion</name>
            <url>https://github.com/jdidion</url>
        </developer>
    </developers>
    <contributors>
        <contributor>
            <name>Ruman Gerst</name>
            <url>https://www.leibniz-hki.de/en/asb-staff-details.html?member=1027</url>
        </contributor>
        <contributor>
            <name>Zoltán Cseresnyés</name>
            <url>https://www.leibniz-hki.de/en/asb-staff-details.html?member=144</url>
        </contributor>
        <contributor>
            <name>Marc Thilo Figge</name>
            <url>https://www.leibniz-hki.de/en/staff-details.html?member=81</url>
        </contributor>
    </contributors>
    <mailingLists>
        <mailingList>
            <name>HKI Jena</name>
            <archive>https://www.leibniz-hki.de/de/angewandte-systembiologie.html</archive>
        </mailingList>
    </mailingLists>
    <scm>
        <connection>scm:git:https://github.com/applied-systems-biology/jipipe</connection>
        <developerConnection>scm:git:https://github.com/applied-systems-biology/jipipe</developerConnection>
        <tag>HEAD</tag>
        <url>https://github.com/applied-systems-biology/jipipe</url>
    </scm>
    <issueManagement>
        <system>GitHub Issues</system>
        <url>https://github.com/applied-systems-biology/jipipe/issues</url>
    </issueManagement>
    <ciManagement>
        <system>GitHub CI</system>
        <url>https://github.com/applied-systems-biology/jipipe</url>
    </ciManagement>
    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>3.1.4</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.14.0</version>
                    <configuration>
                        <release>21</release>
                        <showDeprecation>true</showDeprecation>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>3.1.1</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.3</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.11.2</version>
                <configuration>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.4.2</version>
                <configuration>
                    <archive>
                        <manifestFile>src/main/resources/META-INF/MANIFEST.MF</manifestFile>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>org.hkijena.jipipe.contrib.cwl.cwl1_2.utils.Validator</mainClass>
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
            </plugin>
            <plugin>
                <!-- Disable enforcer, triggered by JDK8 limits introduced by SciJava -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <configuration>
                    <fail>false</fail>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${commonslang.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
        </dependency>
        <dependency>
            <groupId>org.snakeyaml</groupId>
            <artifactId>snakeyaml-engine</artifactId>
            <version>2.9</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.18.0</version>
        </dependency>
    </dependencies>
</project>
