/*
 * Copyright by Zoltán Cseresnyés, Ruman Gerst
 *
 * Research Group Applied Systems Biology - Head: Prof. Dr. Marc Thilo Figge
 * https://www.leibniz-hki.de/en/applied-systems-biology.html
 * HKI-Center for Systems Biology of Infection
 * Leibniz Institute for Natural Product Research and Infection Biology - Hans Knöll Institute (HKI)
 * Adolf-Reichwein-Straße 23, 07745 Jena, Germany
 *
 * The project code is licensed under MIT.
 * See the LICENSE file provided with the code for the full license.
 */

package org.hkijena.jipipe.api.compat;

import org.hkijena.jipipe.api.SetJIPipeDocumentation;
import org.hkijena.jipipe.api.JIPipeProgressInfo;
import org.hkijena.jipipe.api.data.JIPipeData;
import org.hkijena.jipipe.api.data.JIPipeDataTable;

import java.util.Collections;
import java.util.List;

public interface ImageJDataImporter {
    /**
     * Imports JIPipe data from ImageJ
     *
     * @param objects      the ImageJ objects (if available)
     * @param parameters   Parameters of the adapter. Depends entirely on the adapter
     * @param progressInfo the progress info
     * @return Imported JIPipe data as table
     */
    JIPipeDataTable importData(List<Object> objects, ImageJImportParameters parameters, JIPipeProgressInfo progressInfo);

    /**
     * Imports JIPipe data from ImageJ.
     * Returns the first data, otherwise null.
     *
     * @param object       the ImageJ object (if available)
     * @param parameters   Parameters of the adapter. Depends entirely on the adapter
     * @param progressInfo the progress info
     * @return Imported JIPipe data
     */
    default JIPipeData importData(Object object, ImageJImportParameters parameters, JIPipeProgressInfo progressInfo) {
        JIPipeDataTable dataTable = importData(Collections.singletonList(object), parameters, progressInfo);
        if (dataTable.isEmpty())
            return null;
        return dataTable.getData(0, JIPipeData.class, progressInfo);
    }

    /**
     * @return the data class that is generated by this importer
     */
    Class<? extends JIPipeData> getImportedJIPipeDataType();

    /**
     * @return the ImageJ data type that is imported from this importer
     */
    Class<?> getImportedImageJDataType();

    /**
     * A documentation name. Utilizes a {@link SetJIPipeDocumentation} by default (if present). Otherwise, returns the class name.
     *
     * @return the name of this operation
     */
    default String getName() {
        SetJIPipeDocumentation annotation = getClass().getAnnotation(SetJIPipeDocumentation.class);
        if (annotation != null) {
            return annotation.name();
        } else {
            return getClass().getName();
        }
    }

    /**
     * A documentation description. Utilizes a {@link SetJIPipeDocumentation} by default (if present). Otherwise, returns an empty string.
     *
     * @return the description of this operation
     */
    default String getDescription() {
        SetJIPipeDocumentation annotation = getClass().getAnnotation(SetJIPipeDocumentation.class);
        if (annotation != null) {
            return annotation.description();
        } else {
            return "";
        }
    }
}
